export const types = {
  HANDLE: "HANDLE",
  HANDLE1: "HANDLE1",
  HANDLE2: "HANDLE2",
  HANDLE_FOLDER_NAME: "HANDLE_FOLDER_NAME",

  REGISTER_DATA_SEND_REQUEST: "REGISTER_DATA_SEND_REQUEST",
  REGISTER_DATA_SUCCESS: "REGISTER_DATA_SUCCESS",
  REGISTER_DATA_FAILURE: "REGISTER_DATA_FAILURE",

  LOGIN_DATA_SEND_REQUEST: "LOGIN_SEND_REQUEST",
  LOGIN_DATA_SUCCESS: "LOGIN_DATA_SUCCESS",
  LOGIN_DATA_FAILURE: "LOGIN_DATA_FAILURE",

  HANDLEME_SEND_REQUEST: "HANDLEME_SEND_REQUEST",
  HANDLEME_SUCCESS: "HANDLEME_SUCCESS",
  HANDLEME_FAILURE: "HANDLEME_FAILURE",

  CREATE_FOLDER_API_SEND_REQUEST: "CREATE_FOLDER_API_SEND_REQUEST",
  CREATE_FOLDER_API_SUCCESS: "CREATE_FOLDER_API_SUCCESS",
  CREATE_FOLDER_API_FAILURE: "CREATE_FOLDER_API_FAILURE",

  GET_FOLDERS_API_SEND_REQUEST: "GET_FOLDERS_API_SEND_REQUEST",
  GET_FOLDERS_API_SUCCESS: "GET_FOLDERS_API_SUCCESS",
  GET_FOLDERS_API_SUCCESS1: "GET_FOLDERS_API_SUCCESS1",
  GET_FOLDERS_API_FAILURE: "GET_FOLDERS_API_FAILURE",

  GET_CHILD_FOLDERS_API_SEND_REQUEST: "GET_CHILD_FOLDERS_API_SEND_REQUEST",
  GET_CHILD_FOLDERS_API_SUCCESS: "GET_CHILD_FOLDERS_API_SUCCESS",
  GET_CHILD_FOLDERS_API_FAILURE: "GET_CHILD_FOLDERS_API_SEND_REQUEST",

  GET_RENAME_API: "GET_RENAME_API",
  GET_RENAME_API_SUCCESS: "GET_RENAME_API_SUCCESS",
  GET_RENAME_API_FAILURE: "GET_RENAME_API_FAILURE",

  SHOW_ALERT: "SHOW_ALERT",
  OPEN_FOLDER_ACTION: "OPEN_FOLDER_ACTION",
};
