export const types = {
    HANDLE:"HANDLE",
    HANDLE1: "HANDLE1",
    HANDLE2:"HANDLE2",

    REGISTER_DATA_SEND_REQUEST: "REGISTER_DATA_SEND_REQUEST",
    REGISTER_DATA_SUCCESS: "REGISTER_DATA_SUCCESS",
    REGISTER_DATA_FAILURE: "REGISTER_DATA_FAILURE",


    LOGIN_DATA_SEND_REQUEST: "LOGIN_SEND_REQUEST",
    LOGIN_DATA_SUCCESS: "LOGIN_DATA_SUCCESS",
    LOGIN_DATA_FAILURE: "LOGIN_DATA_FAILURE",

    HANDLEME_SEND_REQUEST:"HANDLEME_SEND_REQUEST",
    HANDLEME_SUCCESS:"HANDLEME_SUCCESS",
    HANDLEME_FAILURE:"HANDLEME_FAILURE",
   
  };
  